services:
  nginx:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "8080:80"
    networks:
      - junhee-network
networks:
  junhee-network:
    driver: bridge
